@URI = http://localhost:5183/api


POST {{URI}}/auth/register
Content-Type: application/json


{
    "name": "User3",
    "surname": "User3",
    "email": "user4@yahoo.com",
    "password": "user3"
}

###

POST {{URI}}/auth/login
Content-Type: application/json


{
    "email": "admin",
    "password": "admin"
}


###
GET {{URI}}/bf27bd7c-66cc-4f83-ba1f-0620412bf8fa

###
GET {{URI}}/e35daaba-5a9e-43a2-9305-3dead8296fe0/events


###
PUT {{URI}}
Content-Type: application/json

{
    "userId": "f0024d38-7d87-4298-9093-d262318c4b46",
    "name": "User2",
    "surname": "User2",
}


###

DELETE {{URI}}/users/8494c24c-b90b-4db4-85d6-27b793e3a592



###
GET {{URI}}/users/9055c016-1660-454c-909f-d9284b593486/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwZjY4NzYwLWE4YmItNGE1Yy1hODc4LWI0Yjc2ZDMxYzJjNyIsInJvbGUiOiJBZG1pbiIsImV4cCI6MTczNDE4NjA1NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTgzLyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE4My8ifQ.36f_gadxNbB-S43DL1HMCgd0tYhAHzSG8GqTxpOR1sk

###
GET {{URI}}/users/d5f8c553-43f9-4a1f-b179-52d695384dd4/events